name: Terraform
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
  merge_group:
    types: [checks_requested]
    branches: [main]

jobs:
  terraform-apply:
    if: github.event_name == 'merge_group'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.9
          terraform_wrapper: false
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install AWS cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
      - name: Install jd
        run: |
          curl -L "https://github.com/josephburnett/jd/releases/download/v2.5.0/jd-amd64-linux" -o /usr/local/bin/jd
          chmod +x /usr/local/bin/jd
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Get PR Number
        id: extract_pr
        run: |
          if [[ "${GITHUB_REF}" =~ ^refs/heads/gh-readonly-queue/main/pr-([0-9]+)-.+$ ]]; then
            echo "pr_number=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "No PR number found"
            exit 1
          fi
      - name: Initialize Terraform
        run: terraform init
      - name: Get terraform plan from s3
        env:
          GH_REPO: "${{ github.repository }}"
          GH_PR_NUMBER: "${{ steps.extract_pr.outputs.pr_number }}"
          S3_BUCKET: "terraform-139727352662-eu-west-1"
        run: |
          plan_file=$(aws s3api list-objects \
              --bucket $S3_BUCKET \
              --prefix  $GH_REPO/$GH_PR_NUMBER/ \
              --output text \
              --query "Contents[-1].Key")
          aws s3 cp "s3://$S3_BUCKET/$plan_file" existing.tfplan
      - name: Create new terraform plan
        run: terraform plan -out=current.tfplan
      - name: Compare terraform plans
        run: |
          if jd -opts='[{"@": ["timestamp"], "^": ["DIFF_OFF"]}]' \
                <(terraform show -json existing.tfplan) \
                <(terraform show -json current.tfplan); then
            echo "exit_code=0" >> $GITHUB_OUTPUT
          else
            echo "exit_code=$?" >> $GITHUB_OUTPUT
          fi
      - name: Cancel plan
        if: steps.compare_terraform_plans.outputs.exit_code == '1'
        run: |
          plan_output=$(terraform show -no-color current.tfplan | head -c 60000)
          {
            echo 'Plan changed since last commit. Please review the new plan and re-submit.'
            echo '```'
            echo "$plan_output"
            echo '```'
          } > plan_output.txt
          gh pr comment ${{ github.event.pull_request.number }} --body-file=plan_output.txt
          exit 1
      - name: Apply plan
        if: steps.compare_terraform_plans.outputs.exit_code == '0'
        run: |
          output=$(terraform apply -auto-approve current.tfplan)
          {
            echo 'Plan applied successfully. Output:'
            echo '```'
            echo "$output"
            echo '```'
          } > output.txt
          gh pr comment ${{ github.event.pull_request.number }} --body-file=output.txt || true

  terraform-plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.9
          terraform_wrapper: false
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install AWS cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Initialize Terraform
        run: terraform init
      - name: Terraform plan
        run: terraform plan -out=out.tfplan
      - name: Save Terraform plan in s3
        env:
          GH_REPO: "${{ github.repository }}"
          GH_PR_NUMBER: "${{ github.event.pull_request.number }}"
          S3_BUCKET: "terraform-139727352662-eu-west-1"
        run: |
          plane_time=$(terraform show -json out.tfplan | jq -r .timestamp)
          plan_file=$(date -u -d "$plane_time" +"%Y-%m-%dT%H-%M-%SZ").tfplan
          aws s3 cp out.tfplan "s3://$S3_BUCKET/$GH_REPO/$GH_PR_NUMBER/$plan_file"
      - name: Write plan to PR comment
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          plan_output=$(terraform show -no-color out.tfplan | head -c 60000)
          {
            echo '```'
            echo "$plan_output"
            echo '```'
          } > plan_output.txt
          gh pr comment ${{ github.event.pull_request.number }} --body-file=plan_output.txt
